ARTIST = "ARTIST"
ALBUMARTIST = "ALBUMARTIST"
ALBUM = "ALBUM"
TITLE = "TITLE"
DATE = "DATE"
GENRE = "GENRE"
TRACKNUMBER = "TRACKNUMBER"
TOTALTRACKS = "TOTALTRACKS"
DISCNUMBER = "DISCNUMBER"
TOTALDISCS = "TOTALDISCS"
COMPOSER = "COMPOSER"
COMMENT = "COMMENT"
REPLAYGAIN_TRACK_GAIN = "REPLAYGAIN_TRACK_GAIN"
REPLAYGAIN_ALBUM_GAIN = "REPLAYGAIN_ALBUM_GAIN"

REQUIRED_TAGS = {
    ARTIST,
    ALBUM,
    TITLE,
}

ALBUM_TAGS = {
    ALBUMARTIST,
    ALBUM,
    DATE,
    GENRE,
    TOTALTRACKS,
    TOTALDISCS,
}

TRACK_TAGS = {
    ARTIST,
    TITLE,
    TRACKNUMBER,
    DISCNUMBER,
    COMPOSER,
    COMMENT,
}
